services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: always
    env_file:
      - ./.env
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
