services:
  bot:
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile

    restart: always
    env_file:
      - path: .env
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
